In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D ,MaxPooling2D ,Flatten ,Dense
import psutil
from matplotlib import image as mpin

In [2]:

x_train=np.loadtxt("input.csv" ,delimiter=',')
y_train=np.loadtxt("labels.csv",delimiter=',')
x_test=np.loadtxt("input_test.csv",delimiter=',')
y_test=np.loadtxt("labels_test.csv",delimiter=',')

In [3]:

x_train=x_train.reshape(len(x_train),100,100,3)
y_train=y_train.reshape(len(y_train),1)
x_test=x_test.reshape(len(x_test),100,100,3)
y_test=y_test.reshape(len(y_test),1)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
print(x_train[1,:])

x_test[1,:]

(2000, 100, 100, 3)
(2000, 1)
(400, 100, 100, 3)
(400, 1)
[[[131. 128. 135.]
  [160. 157. 164.]
  [198. 192. 204.]
  ...
  [250. 249. 247.]
  [255. 255. 253.]
  [250. 249. 245.]]

 [[140. 137. 144.]
  [127. 124. 131.]
  [120. 114. 124.]
  ...
  [251. 253. 252.]
  [254. 255. 253.]
  [254. 255. 251.]]

 [[204. 202. 207.]
  [187. 185. 190.]
  [147. 142. 148.]
  ...
  [249. 255. 255.]
  [238. 247. 242.]
  [232. 241. 236.]]

 ...

 [[174. 182. 195.]
  [172. 180. 193.]
  [178. 186. 197.]
  ...
  [ 87. 114.  97.]
  [ 75.  99.  83.]
  [ 80. 105.  86.]]

 [[166. 173. 189.]
  [164. 172. 185.]
  [172. 180. 193.]
  ...
  [ 78. 106.  84.]
  [ 72.  97.  76.]
  [ 77. 102.  81.]]

 [[173. 180. 196.]
  [172. 179. 195.]
  [174. 182. 195.]
  ...
  [ 63.  91.  69.]
  [ 62.  87.  65.]
  [ 71.  96.  74.]]]


array([[[223., 211., 163.],
        [223., 209., 160.],
        [244., 228., 179.],
        ...,
        [252., 253., 255.],
        [254., 255., 255.],
        [245., 246., 250.]],

       [[255., 246., 206.],
        [254., 241., 199.],
        [255., 251., 206.],
        ...,
        [252., 252., 250.],
        [255., 255., 253.],
        [255., 255., 253.]],

       [[255., 249., 222.],
        [254., 243., 213.],
        [255., 246., 212.],
        ...,
        [241., 239., 227.],
        [165., 163., 151.],
        [145., 143., 131.]],

       ...,

       [[136., 131., 128.],
        [174., 170., 167.],
        [181., 177., 176.],
        ...,
        [ 47.,  50.,  55.],
        [ 46.,  49.,  56.],
        [ 47.,  50.,  57.]],

       [[173., 165., 162.],
        [182., 177., 174.],
        [167., 162., 159.],
        ...,
        [ 70.,  74.,  77.],
        [ 70.,  73.,  78.],
        [ 70.,  73.,  78.]],

       [[141., 133., 130.],
        [133., 125., 122.],
        [121., 1

In [4]:
x_train=x_train/255.0
x_test=x_test/255.0
print(x_train[1])
print(x_test[1])

[[[0.51372549 0.50196078 0.52941176]
  [0.62745098 0.61568627 0.64313725]
  [0.77647059 0.75294118 0.8       ]
  ...
  [0.98039216 0.97647059 0.96862745]
  [1.         1.         0.99215686]
  [0.98039216 0.97647059 0.96078431]]

 [[0.54901961 0.5372549  0.56470588]
  [0.49803922 0.48627451 0.51372549]
  [0.47058824 0.44705882 0.48627451]
  ...
  [0.98431373 0.99215686 0.98823529]
  [0.99607843 1.         0.99215686]
  [0.99607843 1.         0.98431373]]

 [[0.8        0.79215686 0.81176471]
  [0.73333333 0.7254902  0.74509804]
  [0.57647059 0.55686275 0.58039216]
  ...
  [0.97647059 1.         1.        ]
  [0.93333333 0.96862745 0.94901961]
  [0.90980392 0.94509804 0.9254902 ]]

 ...

 [[0.68235294 0.71372549 0.76470588]
  [0.6745098  0.70588235 0.75686275]
  [0.69803922 0.72941176 0.77254902]
  ...
  [0.34117647 0.44705882 0.38039216]
  [0.29411765 0.38823529 0.3254902 ]
  [0.31372549 0.41176471 0.3372549 ]]

 [[0.65098039 0.67843137 0.74117647]
  [0.64313725 0.6745098  0.7254902 ]


In [5]:
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(100, 100, 3)),
    MaxPooling2D((2, 2)),  # Corrected the pool_size argument
    Conv2D(32, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),  # Corrected the pool_size argument
    Flatten(),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])


In [6]:
model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])

In [7]:
model.fit(x_train,y_train,epochs=10,batch_size=32)

Epoch 1/10
63/63 [==============================] - 6s 81ms/step - loss: 0.7627 - accuracy: 0.5020
Epoch 2/10
63/63 [==============================] - 5s 81ms/step - loss: 0.6834 - accuracy: 0.5645
Epoch 3/10
63/63 [==============================] - 5s 80ms/step - loss: 0.6475 - accuracy: 0.6255
Epoch 4/10
63/63 [==============================] - 5s 87ms/step - loss: 0.5728 - accuracy: 0.6920
Epoch 5/10
63/63 [==============================] - 5s 76ms/step - loss: 0.4687 - accuracy: 0.7660
Epoch 6/10
63/63 [==============================] - 5s 78ms/step - loss: 0.3610 - accuracy: 0.8520
Epoch 7/10
63/63 [==============================] - 5s 81ms/step - loss: 0.2525 - accuracy: 0.9020
Epoch 8/10
63/63 [==============================] - 5s 80ms/step - loss: 0.1551 - accuracy: 0.9445
Epoch 9/10
63/63 [==============================] - 5s 84ms/step - loss: 0.0758 - accuracy: 0.9785
Epoch 10/10
63/63 [==============================] - 5s 87ms/step - loss: 0.0460 - accuracy: 0.9890


In [8]:
model.evaluate(x_test,y_test)

13/13 [==============================] - 1s 38ms/step - loss: 1.4015 - accuracy: 0.6725


[1.4014511108398438, 0.6725000143051147]

In [13]:
index=random.randint(0,len(x_test))
y_predicted=model.predict(x_test[index,:].reshape(1,100,100,3))
print(y_predicted)
if(y_predicted>0.5):
    print('dog')
    print(index)
else:
    print('cat')
    print(index)
    
    
#if a<=200 cat else dog

1/1 [==============================] - 0s 17ms/step
[[0.14755295]]
cat
105
